services:
  aproxima:
    image: node:18-alpine
    container_name: aproxima-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "npm install && npm run build && npm start"