services:
  aproxima:
    image: node:18-alpine
    container_name: aproxima-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    command: >
      sh -c "
        apk add --no-cache git &&
        cd /tmp &&
        rm -rf aproxima &&
        git clone https://github.com/KallebyX/aproxima.git &&
        cd aproxima &&
        npm install &&
        npm run build &&
        npm start
      "