services:
  aproxima:
    image: node:18-alpine
    container_name: aproxima-app
    restart: unless-stopped
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    command: >
      sh -c "
        apk add --no-cache git &&
        rm -rf /tmp/repo &&
        git clone https://github.com/KallebyX/aproxima.git /tmp/repo &&
        cp -r /tmp/repo/* /app/ &&
        cp /tmp/repo/.* /app/ 2>/dev/null || true &&
        npm install &&
        npm run build &&
        npm start
      "