services:
  aproxima:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aproxima-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000